[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

# 这个配置确保所有路由都重定向到index.html，以支持React Router的单页应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
